187 add support for jarl major contests
w7sst/MorseRunner pull request #192
Opened 2023-02-27 12:39 UTC by jr8ppg

Added support for JARL major contests.

2023-02-27 17:03 UTC, w7sst requested changes

2023-02-27 21:06 UTC, w7sst requested changes
This is great to see a new contest implemented by you. Thank you for your efforts. Please review my comments. I will re-review after you make a few changes and respond. Thanks again.

2023-02-28 01:21 UTC, jr8ppg commented on ACAG.pas
> +        rec := nil;
done

2023-02-28 01:28 UTC, jr8ppg commented on Ini.pas
> +    (Name: '[JA]ALL JA Contest';
I understand about "Name".
Is it okay to leave the "Key" value as is?

2023-02-28 01:33 UTC, jr8ppg commented on DIC_ACAG.TXT
> +!!Order!!, Call, Exch1, UserText,
Change to comma delimited to match other contests.
Change the file name from DIC_ALLJA.TXT to JARL_ALLJA.TXT.

2023-02-28 01:44 UTC, jr8ppg commented on Main.dfm
> +      Font.Charset = SHIFTJIS_CHARSET
oh
Since it was edited with the Japanese version of Delphi, it became SHIFT-JIS.
Shouldn't have committed.

2023-02-28 01:48 UTC, jr8ppg commented on Main.dfm
> +      Font.Charset = SHIFTJIS_CHARSET
done

2023-02-28 03:33 UTC, w7sst commented on Ini.pas
> +    (Name: '[JA]ALL JA Contest';
Yes, the key value is perfect as it is.

2023-02-28 08:29 UTC, w7sst commented on Ini.pas
> +    (Name: '[JA]ALL JA Contest';
The new names look really good in the menu now. thanks!

2023-02-28 08:41 UTC, w7sst commented on ACAG.pas
> +//
I understand now. You are using the city, gun, or ku numbers as the multiplier string. Okay. this looks fine.

Perhaps you could add to the comment:
`// The extracted multiplier string is simply the <city|gun|ku> location number from Exchange Field 2.`

2023-02-28 13:04 UTC, jr8ppg commented on ALLJA.pas
> +    Result := S;
done

2023-02-28 13:06 UTC, jr8ppg commented on ACAG.pas
> +function TACAG.getExch2(id:integer): string;    // returns section info (e.g. 3)
Enhanced comment for ExtractMultiplier.

2023-02-28 13:06 UTC, jr8ppg commented on ALLJA.pas
> +function TALLJA.getExch2(id:integer): string;    // returns section info (e.g. 3)
Enhanced comment for ExtractMultiplier.

2023-02-28 13:06 UTC, jr8ppg commented on ACAG.pas
> +//
Enhanced comment for ExtractMultiplier.
done

2023-02-28 13:16 UTC, jr8ppg commented on Log.pas
> +        , MultStr, Err, format('%.2d', [TrueWpm]));
Line 602 extracts the multiplier element from the exchange number and sets it to MultiStr.
I think you're right in this contest.

` Qso.MultStr := Tst.ExtractMultiplier(Qso);
`

2023-02-28 15:45 UTC, w7sst commented on ACAG.pas
> +//
It is very clear now. This will also help future readers of this code. Thank you.

You can mark this conversation resolved.

2023-02-28 15:46 UTC, w7sst commented on ALLJA.pas
> +//
Very clear. Thank you. You can mark this as resolved once you are complete.

2023-02-28 15:46 UTC, w7sst commented on ALLJA.pas
> +    Result := S;
Very clear. Thank you.

2023-02-28 15:55 UTC, w7sst commented on ACAG.pas
> +function TACAG.getExch2(id:integer): string;    // returns section info (e.g. 3)
Thank you. You can mark this as Resolved.

2023-02-28 15:56 UTC, w7sst commented on Log.pas
> +        , MultStr, Err, format('%.2d', [TrueWpm]));
Agreed.

2023-02-28 16:00 UTC, w7sst commented on ACAG.pas
> +function TACAG.getExch2(id:integer): string;    // returns section info (e.g. 3)
I marked this as Resolved.

2023-02-28 16:01 UTC, w7sst commented on ACAG.pas
> +//
I marked this as Resolved.

2023-02-28 21:08 UTC, ct7aup approved these changes

2023-03-01 03:05 UTC, w7sst approved these changes
Thank you for your implementation of JARL Contests. Your changes look great.

I will publish a pre-release build in the next few days after finishing up some work on CW timing issues with Farnsworth timing for the upcoming K1USN SST Contest.

Thank you again. We appreciate your help.

I will merge this change now.

2023-03-01 03:18 UTC, merged